{
    "name": "Education Admission",
    "version": "19.0.1.0.0",
    "category": "Tools",
    "summary": "Manage education admission applications",
    "author": "Muslim Foda",
    "maintainer": "Muslim Foda",
    "website": "https://github.com/muslim-foda/Education",
    "depends": [
        "base",
        "mail",
        "education_core",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/education_enrollment_views.xml",
        "views/aeducation_application_views.xml",
        "views/education_menu_views.xml",
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True,
}
